# demo.tape

Output assets/demo.gif

Set Shell "bash"
Set FontSize 16
Set Width 800
Set Height 500
Set Theme "Catppuccin Mocha"
Set Padding 20
Set PlaybackSpeed 1.5

Type "go run ."
Enter
Sleep 2s

Type "map"
Enter
Sleep 2s

Type "explore pastoria-city-area"
Enter
Sleep 2s

Type "catch magikarp"
Enter
Sleep 1s
Type "Splash"
Enter
Sleep 2s

Type "inspect Splash"
Enter
Sleep 3s

Type "exit"
Enter
Sleep 1s
